// src/app/terms/page.tsx
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - Luminael AI',
  description: 'Luminael AI Terms of Service.',
};

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-3xl prose dark:prose-invert lg:prose-xl">
      <h1 className="text-3xl font-bold mb-6 font-headline text-center">Terms of Service</h1>
      <p className="mb-6 text-center text-muted-foreground">Last Updated: {new Date().toLocaleDateString()}</p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mt-6 mb-4 font-headline">1. Our Philosophy and Service</h2>
        <p>
          Luminael AI (&quot;the Service&quot;) is a free, client-side tool provided by SYNAPPSE. Our mission is to empower everyone to learn, educate themselves, and grow. The Service is provided &quot;as is&quot; with no fees, no user accounts, and no data collection by Luminael AI&apos;s servers regarding your content or API keys. It is a tool for you to use for your own educational purposes.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mt-6 mb-4 font-headline">2. Your Responsibilities</h2>
        <p>As a user of Luminael, you agree to the following:</p>
        <ul className="list-disc list-inside space-y-2 pl-4 my-4">
          <li>
            <strong>Bring Your Own API Key:</strong> You are responsible for obtaining and using your own Google Gemini API key (or other compatible third-party AI model API keys as the Service may support in the future). All API calls made through the Service to such third-party AI models are made using your key, initiated from your browser. You are solely responsible for complying with the respective AI provider&apos;s (e.g., Google&apos;s) API terms of service, usage policies, and any costs you may incur with them. Luminael AI does not have access to, nor does it store, your API key on any server it operates. The key is stored locally in your browser&apos;s storage (IndexedDB) for your convenience.
          </li>
          <li>
            <strong>Content Ownership:</strong> You represent and warrant that you have all necessary rights to any content (text, images, documents) you upload or input into the Service for processing. You retain all ownership of your content and the quizzes or other materials generated from it by the AI models. Luminael AI claims no ownership over your content or the AI-generated output derived from your content and API key.
          </li>
          <li>
            <strong>Acceptable Use:</strong> You agree not to use the Service for any unlawful, harmful, or prohibited purpose. This includes, but is not limited to, generating content that is defamatory, obscene, infringing on intellectual property rights, or violating any applicable laws or regulations. You are responsible for the nature of the content you process and generate using the Service.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mt-6 mb-4 font-headline">3. Disclaimer and Limitation of Liability</h2>
        <p>We provide this tool with the best intentions, but it&apos;s important to understand its limitations:</p>
        <ul className="list-disc list-inside space-y-2 pl-4 my-4">
          <li>
            <strong>No Guarantees:</strong> The Service is provided &quot;as is&quot; and &quot;as available,&quot; without warranty of any kind, express or implied. We do not guarantee the accuracy, completeness, reliability, availability, or timeliness of any information, content, or quizzes generated by the third-party AI models accessed through the Service. AI-generated content can contain inaccuracies or errors; always verify critical information.
          </li>
          <li>
            <strong>No Liability:</strong> To the fullest extent permitted by applicable law, SYNAPPSE and the developer(s) of Luminael AI will not be liable for any direct, indirect, incidental, special, consequential, or punitive damages or losses arising from your use of, or inability to use, the Service. This includes, but is not limited to, any costs associated with your API key usage with third-party providers, data loss (as data is stored client-side), or reliance on information generated by the Service. Your use of the Service is solely at your own risk.
          </li>
          <li>
            <strong>Intellectual Property:</strong> You own your content and the output generated using your content and your API key. We (SYNAPPSE) own the code, design, branding, and overall look and feel of the Luminael AI application. You may not copy, modify, distribute, sell, or lease any part of our Service or its underlying software, nor may you reverse engineer or attempt to extract the source code of that software, except to the extent that laws prohibit these restrictions or you have our written permission.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mt-6 mb-4 font-headline">A Shared Vision</h2>
        <p className="mb-3">
          By using Luminael, you join us in a vision for a world where education is free and accessible to all. We provide the tool; you provide the curiosity. Together, we can create a brighter, more knowledgeable future.
        </p>
      </section>

      <section className="mt-12 pt-6 border-t border-border">
        <h2 className="text-2xl font-semibold mb-4 text-center font-headline">A Note to Our Friends at Google (and other AI Providers)</h2>
        <p className="mb-3 text-center italic text-muted-foreground">
          Luminael is an experiment in radical accessibility and educational empowerment. We believe everyone, everywhere, deserves the right to learn without barriers. By enabling users to leverage their own API keys, we are creating a decentralized, private, and powerful learning tool that respects user privacy and champions the universal right to education. We hope you see this project not as a circumvention, but as an innovation that aligns with the highest ideals of making information universally accessible and useful. Let&apos;s not hinder this journey; let&apos;s champion it together.
        </p>
      </section>

      <section className="mt-8">
         <p className="text-center text-sm text-muted-foreground">
            If you have any questions about these Terms of Service, please contact us. please contact us. Email: synpps@gmailcom Website: synappse.vercel.app or in my personal email mosqueraken16@gmail.com
         </p>
      </section>
    </div>
  );
}
